[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "fastapi-jwt-auth"
version="0.5.1"
authors = ["Libre NZ <github libre.nz>"]
description = "FastAPI JWT Auth"
homepage = "https://github.com/LibreNZ/fastapi-jwt-auth"
repository = "https://github.com/LibreNZ/fastapi-jwt-auth"
classifiers = [
  "Environment :: Web Environment",
  "Intended Audience :: Developers",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.6",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: 3.8",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
  "Topic :: Software Development :: Libraries :: Python Modules"
]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"
pyjwt = {extras = ["crypto"], version = "^2.6.0"}
fastapi = "^0.95.1"
pytest = "^7.3.1"
mkdocs = "^1.4.2"

[tool.poetry.group.test.dependencies]
pytest = "^7.3.1"

[tool.poetry.group.docs.dependencies]
mkdocs = "^1.4.2"

[tool.poetry.group.dev.dependencies]
uvicorn = "^0.22.0"