name: Tests

on: 
  push:
    paths-ignore:
      - '**/README.md'
      - '**/CHANGELOG.md'
  pull_request:
    paths-ignore:
      - '**/README.md'
      - '**/CHANGELOG.md'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
      fail-fast: false
    
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry
        run: pip install poetry
      - name: Disable venv
        run: poetry config --local virtualenvs.create false
      - name: Install Dependencies
        run: poetry install
      - name: Test
        run: bash scripts/tests.sh
