name: Tests

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**/README.md'
      - '**/CHANGELOG.md'
  pull_request:
    paths-ignore:
      - '**/README.md'
      - '**/CHANGELOG.md'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
      fail-fast: false
    
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry
        run: pip install poetry

      - name: Disable venv
        run: poetry config --local virtualenvs.create false

      - name: Install Dependencies
        run: poetry install

      # - name: Test
      #   run: bash scripts/tests.sh

      - name: Run tests
        env:
          REPORT_OUTPUT: md_report.md
        shell: bash
        run: |
          echo "REPORT_FILE=${REPORT_OUTPUT}" >> "$GITHUB_ENV"
          pytest -o log_cli=true --log-cli-level=INFO --md-report --md-report-flavor github --md-report-output "$REPORT_OUTPUT"

      - name: Output reports to the job summary when tests fail
        if: failure()
        shell: bash
        run: |
          if [ -f "$REPORT_FILE" ]; then
            echo "<details><summary>Failed Test Report</summary>" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            cat "$REPORT_FILE" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "</details>" >> $GITHUB_STEP_SUMMARY
          fi